import json

data = {
  "nodes": [
    {"id":"next_config_nextconfig","label":"Next.js Config","file_type":"code","source_file":"next.config.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"package_prdmanagerui","label":"PRD Manager UI Package","file_type":"code","source_file":"package.json","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"api_save_prd_handler","label":"Save PRD API Handler","file_type":"code","source_file":"api/save_prd.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"api_webhook_handler","label":"Webhook API Handler","file_type":"code","source_file":"api/webhook.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"components_diffviewer","label":"DiffViewer Component","file_type":"code","source_file":"components/DiffViewer.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"components_editor","label":"Editor Component","file_type":"code","source_file":"components/Editor.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"components_kanbanboard","label":"KanbanBoard Component","file_type":"code","source_file":"components/KanbanBoard.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"components_nav","label":"Nav Component","file_type":"code","source_file":"components/Nav.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"components_tasktree","label":"TaskTree Component","file_type":"code","source_file":"components/TaskTree.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"lib_apifetch","label":"API Fetch Utility","file_type":"code","source_file":"lib/api-fetch.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"lib_auditlog","label":"Audit Log Library","file_type":"code","source_file":"lib/audit-log.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"lib_prdstore","label":"PRD Store Library","file_type":"code","source_file":"lib/prd-store.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"lib_requireadmin","label":"Require Admin Middleware","file_type":"code","source_file":"lib/require-admin.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"lib_snapshotstore","label":"Snapshot Store Library","file_type":"code","source_file":"lib/snapshot-store.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"lib_sprintstore","label":"Sprint Store Library","file_type":"code","source_file":"lib/sprint-store.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"lib_taskstore","label":"Task Store Library","file_type":"code","source_file":"lib/task-store.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"pages_admin","label":"Admin Page","file_type":"code","source_file":"pages/admin.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"ext_vercel_kv","label":"Vercel KV Store","file_type":"code","source_file":"package.json","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"ext_github_api","label":"GitHub REST API","file_type":"code","source_file":"api/save_prd.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"ext_diff_lib","label":"diff npm Library","file_type":"code","source_file":"package.json","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_xuser_header","label":"X-User Auth Header Pattern","file_type":"rationale","source_file":"lib/api-fetch.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_audit_kv_sorted_set","label":"Audit Log KV Sorted Set Pattern","file_type":"rationale","source_file":"lib/audit-log.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_prd_versioning","label":"Semantic Version Bumping for PRDs","file_type":"rationale","source_file":"lib/prd-store.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_task_hierarchy","label":"Hierarchical Task Tree with Auto-numbering","file_type":"rationale","source_file":"lib/task-store.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_proposal_promotion","label":"Proposal-to-Version Promotion Workflow","file_type":"rationale","source_file":"lib/prd-store.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_snapshot_full_state","label":"Full-State Snapshot Capture","file_type":"rationale","source_file":"lib/snapshot-store.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_kanban_orphan_subtask","label":"Orphan Subtask Cross-Column Display","file_type":"rationale","source_file":"components/KanbanBoard.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None}
  ],
  "edges": [
    {"source":"components_editor","target":"lib_apifetch","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"components/Editor.js","source_location":None,"weight":1.0},
    {"source":"components_kanbanboard","target":"lib_apifetch","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"components/KanbanBoard.js","source_location":None,"weight":1.0},
    {"source":"components_nav","target":"lib_apifetch","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"components/Nav.js","source_location":None,"weight":1.0},
    {"source":"components_tasktree","target":"lib_apifetch","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"components/TaskTree.js","source_location":None,"weight":1.0},
    {"source":"pages_admin","target":"lib_apifetch","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"pages/admin.js","source_location":None,"weight":1.0},
    {"source":"pages_admin","target":"components_nav","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"pages/admin.js","source_location":None,"weight":1.0},
    {"source":"lib_snapshotstore","target":"lib_prdstore","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/snapshot-store.js","source_location":None,"weight":1.0},
    {"source":"lib_snapshotstore","target":"lib_taskstore","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/snapshot-store.js","source_location":None,"weight":1.0},
    {"source":"lib_snapshotstore","target":"ext_vercel_kv","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/snapshot-store.js","source_location":None,"weight":1.0},
    {"source":"lib_prdstore","target":"ext_vercel_kv","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/prd-store.js","source_location":None,"weight":1.0},
    {"source":"lib_taskstore","target":"ext_vercel_kv","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/task-store.js","source_location":None,"weight":1.0},
    {"source":"lib_auditlog","target":"ext_vercel_kv","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/audit-log.js","source_location":None,"weight":1.0},
    {"source":"lib_sprintstore","target":"ext_vercel_kv","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/sprint-store.js","source_location":None,"weight":1.0},
    {"source":"api_save_prd_handler","target":"ext_github_api","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"api/save_prd.js","source_location":None,"weight":1.0},
    {"source":"api_webhook_handler","target":"ext_github_api","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"api/webhook.js","source_location":None,"weight":1.0},
    {"source":"components_diffviewer","target":"ext_diff_lib","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"components/DiffViewer.js","source_location":None,"weight":1.0},
    {"source":"lib_apifetch","target":"concept_xuser_header","relation":"implements","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/api-fetch.js","source_location":None,"weight":1.0},
    {"source":"lib_requireadmin","target":"concept_xuser_header","relation":"implements","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/require-admin.js","source_location":None,"weight":1.0},
    {"source":"lib_auditlog","target":"concept_xuser_header","relation":"implements","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/audit-log.js","source_location":None,"weight":1.0},
    {"source":"lib_auditlog","target":"concept_audit_kv_sorted_set","relation":"implements","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/audit-log.js","source_location":None,"weight":1.0},
    {"source":"lib_prdstore","target":"concept_prd_versioning","relation":"implements","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/prd-store.js","source_location":None,"weight":1.0},
    {"source":"lib_prdstore","target":"concept_proposal_promotion","relation":"implements","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/prd-store.js","source_location":None,"weight":1.0},
    {"source":"lib_taskstore","target":"concept_task_hierarchy","relation":"implements","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/task-store.js","source_location":None,"weight":1.0},
    {"source":"lib_snapshotstore","target":"concept_snapshot_full_state","relation":"implements","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/snapshot-store.js","source_location":None,"weight":1.0},
    {"source":"components_kanbanboard","target":"concept_kanban_orphan_subtask","relation":"implements","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"components/KanbanBoard.js","source_location":None,"weight":1.0},
    {"source":"components_tasktree","target":"concept_task_hierarchy","relation":"references","confidence":"INFERRED","confidence_score":0.95,"source_file":"components/TaskTree.js","source_location":None,"weight":1.0},
    {"source":"components_kanbanboard","target":"concept_task_hierarchy","relation":"references","confidence":"INFERRED","confidence_score":0.85,"source_file":"components/KanbanBoard.js","source_location":None,"weight":1.0},
    {"source":"pages_admin","target":"lib_auditlog","relation":"references","confidence":"INFERRED","confidence_score":0.95,"source_file":"pages/admin.js","source_location":None,"weight":1.0},
    {"source":"pages_admin","target":"lib_snapshotstore","relation":"references","confidence":"INFERRED","confidence_score":0.95,"source_file":"pages/admin.js","source_location":None,"weight":1.0},
    {"source":"components_editor","target":"lib_prdstore","relation":"shares_data_with","confidence":"INFERRED","confidence_score":0.85,"source_file":"components/Editor.js","source_location":None,"weight":1.0},
    {"source":"lib_snapshotstore","target":"lib_prdstore","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/snapshot-store.js","source_location":None,"weight":1.0},
    {"source":"api_webhook_handler","target":"api_save_prd_handler","relation":"conceptually_related_to","confidence":"INFERRED","confidence_score":0.75,"source_file":"api/webhook.js","source_location":None,"weight":1.0},
    {"source":"components_nav","target":"concept_xuser_header","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"components/Nav.js","source_location":None,"weight":1.0},
    {"source":"lib_prdstore","target":"lib_taskstore","relation":"conceptually_related_to","confidence":"INFERRED","confidence_score":0.85,"source_file":"lib/snapshot-store.js","source_location":None,"weight":1.0},
    {"source":"concept_proposal_promotion","target":"concept_prd_versioning","relation":"rationale_for","confidence":"INFERRED","confidence_score":0.85,"source_file":"lib/prd-store.js","source_location":None,"weight":1.0},
    {"source":"components_tasktree","target":"components_kanbanboard","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.85,"source_file":"components/TaskTree.js","source_location":None,"weight":1.0}
  ],
  "hyperedges": [
    {"id":"kv_persistence_layer","label":"Vercel KV Persistence Layer","nodes":["lib_prdstore","lib_taskstore","lib_auditlog","lib_sprintstore","lib_snapshotstore","ext_vercel_kv"],"relation":"participate_in","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/prd-store.js"},
    {"id":"auth_xuser_pattern","label":"X-User Header Auth Pattern","nodes":["lib_apifetch","lib_requireadmin","lib_auditlog","concept_xuser_header"],"relation":"implement","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"lib/api-fetch.js"},
    {"id":"task_management_ui","label":"Task Management UI Components","nodes":["components_tasktree","components_kanbanboard","lib_taskstore","lib_apifetch"],"relation":"implement","confidence":"INFERRED","confidence_score":0.95,"source_file":"components/TaskTree.js"},
    {"id":"admin_panel_features","label":"Admin Panel Feature Set","nodes":["pages_admin","lib_auditlog","lib_snapshotstore","lib_requireadmin","components_nav"],"relation":"implement","confidence":"INFERRED","confidence_score":0.95,"source_file":"pages/admin.js"},
    {"id":"github_integration","label":"GitHub Integration","nodes":["api_save_prd_handler","api_webhook_handler","ext_github_api"],"relation":"participate_in","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"api/save_prd.js"}
  ],
  "input_tokens": 0,
  "output_tokens": 0
}

out_path = r"C:\HVWork\PRD_Manager\graphify-out\.graphify_chunk_01.json"
with open(out_path, "w") as f:
    json.dump(data, f, separators=(",", ":"))
print("Written:", out_path)
